name: Feature request
description: Suggest an idea or an improvement
labels: [enhancement]
body:
  - type: textarea
    id: problem
    attributes:
      label: What problem would it solve?
    validations:
      required: true
  - type: textarea
    id: idea
    attributes:
      label: Your idea
      description: How you imagine it working.
    validations:
      required: true
  - type: textarea
    id: alternatives
    attributes:
      label: Alternatives you considered
